### ISSUE TITLE
404 Error onload

### ISSUE THREAD

**Issue by semaf** [shameemreza/instagram-widget#1]
Hey Shameem,

Thanks for the nice code but I think it needs to be updated.

I get the error: "An error occured. See console for the details" on the Image.
In the console are not errors I could see.

`https://domain.com/instagram/api/?path=%2Fv1%2Fusers%2Fshameemreza_%2F&callback=jQuery112403088233881973521_1542842705477&_=1542842705478`

**Comment by shameemreza** [comment]
There is an issue with your path. If you correct it then it will be resolved.
