### ISSUE TITLE
service is unavailable now

### ISSUE THREAD

**Issue by DheenadhayalanP** [shameemreza/instagram-widget#3]
I got a result 

> An error occurred. See console for the details.

In console, I can see the log below

> [#shameem_0: undefined | service is unavailable now]

Please check the code in here
[http://hitandget.epizy.com/instagram/](http://hitandget.epizy.com/instagram/)

**Comment by shameemreza** [comment]
You need to specify an Instagram Client ID. You can get it here http://instagram.com/developer/clients/register/
